name: Action CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Verify action syntax
        id: npm-version
        uses: "./"
        with:
          cmd: test
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          push: true
          tags: :latest
